### use balance
 POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber":  "1000000001",
  "amount": 1000
}

### use balance2
 POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000001",
  "amount": 1000
}

### cancel balance
 POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId" : "802e3db873e64d5eb1da739b15957e93"
  , "accountNumber" : "1000000001"
  , "amount": 1000
}

### get transacitonQuery
GET http://localhost:8080/transaction/905c73ae486b46889972aadc90d686be


